name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub (optional, for pushing images)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

      # Build Docker image
      - name: Build Docker image
        run: docker-compose -f docker-compose.yml build app

      # Start services and run tests
      - name: Run tests with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d mongo
          docker-compose -f docker-compose.yml run --rm app pytest tests/
          docker-compose -f docker-compose.yml down

      # Tag and push Docker image (optional, only on main branch push)
      - name: Tag and push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker tag library-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/library-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/library-app:latest