name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker-compose -f docker-compose.yml build app

      - name: Run tests with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d mongo
          docker-compose -f docker-compose.yml run --rm app pytest tests/
          docker-compose -f docker-compose.yml down